/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.metodoP;

import Sistema.Carrito;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import movimiento.MoverComp;

/**
 *
 * @author CRISTHIAN
 */
public class metodoPago extends javax.swing.JPanel {

    /**
     * Creates new form metodoPago
     */
    public metodoPago() {
        initComponents();
        plin.setCursor(new Cursor(HAND_CURSOR));
        visa.setCursor(new Cursor(HAND_CURSOR));
        yape.setCursor(new Cursor(HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        plin = new Sistema.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        visa = new Sistema.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        yape = new Sistema.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        metodo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione método de pago:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 190, 40));

        plin.setBackground(new java.awt.Color(204, 204, 204));
        plin.setForeground(new java.awt.Color(204, 204, 204));
        plin.setRoundBottomLeft(25);
        plin.setRoundBottomRight(25);
        plin.setRoundTopLeft(25);
        plin.setRoundTopRight(25);
        plin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plinMouseClicked(evt);
            }
        });
        plin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plin.png"))); // NOI18N
        plin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 91, 91));

        add(plin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 110, 110));

        visa.setBackground(new java.awt.Color(204, 204, 204));
        visa.setForeground(new java.awt.Color(204, 204, 204));
        visa.setRoundBottomLeft(25);
        visa.setRoundBottomRight(25);
        visa.setRoundTopLeft(25);
        visa.setRoundTopRight(25);
        visa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visaMouseClicked(evt);
            }
        });
        visa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visa (1).png"))); // NOI18N
        visa.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 110));

        yape.setBackground(new java.awt.Color(204, 204, 204));
        yape.setForeground(new java.awt.Color(204, 204, 204));
        yape.setRoundBottomLeft(25);
        yape.setRoundBottomRight(25);
        yape.setRoundTopLeft(25);
        yape.setRoundTopRight(25);
        yape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yapeMouseClicked(evt);
            }
        });
        yape.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yape (1).png"))); // NOI18N
        yape.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        add(yape, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, 110));

        next.setText("Continuar");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 100, 30));

        metodo.setBackground(new java.awt.Color(102, 102, 102));
        metodo.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        metodo.setForeground(new java.awt.Color(102, 102, 102));
        metodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(metodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 140, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void visaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visaMouseClicked
        visa.setBackground(new Color(153,153,153));
        plin.setBackground(new Color(204,204,204));
        yape.setBackground(new Color(204,204,204));
        metodo.setText("Visa");
    }//GEN-LAST:event_visaMouseClicked

    private void yapeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yapeMouseClicked
        visa.setBackground(new Color(204,204,204));
        plin.setBackground(new Color(204,204,204));
        yape.setBackground(new Color(153,153,153));
        metodo.setText("Yape");
    }//GEN-LAST:event_yapeMouseClicked

    private void plinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plinMouseClicked
        visa.setBackground(new Color(204,204,204));
        yape.setBackground(new Color(204,204,204));
        plin.setBackground(new Color(153,153,153));
        metodo.setText("Plin");
    }//GEN-LAST:event_plinMouseClicked
    public void showPanel(JPanel m){
            m.setSize(540, 400);
            m.setLocation(0, 0);
            Carrito.contenedor.removeAll();
            Carrito.contenedor.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
            Carrito.contenedor.revalidate();
            Carrito.contenedor.repaint();
        }
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (metodo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Seleccione un método de pago.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
        revisar m = new revisar();
        showPanel(m);
        MoverComp.Derecha(Carrito.cambio, 2, 1, 342);
        Carrito.lblrevisar.setForeground(Color.BLACK);
        Carrito.lblmetodo.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel metodo;
    private javax.swing.JButton next;
    private Sistema.PanelRound plin;
    private Sistema.PanelRound visa;
    private Sistema.PanelRound yape;
    // End of variables declaration//GEN-END:variables
}
